//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.04 at 11:00:12 AM IST
//


package com.echo.model.agency;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>
 * Java class for CustodianResponse complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustodianResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgentReference" type="{}AgentReference"/>
 *         &lt;element name="MessageType" type="{}MessageType"/>
 *         &lt;element name="OrderStatus">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="code" use="required" type="{}OrderStatusCode" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CertificateType" type="{}CertificateType" minOccurs="0"/>
 *         &lt;element name="CertificateText" type="{}CDATA" minOccurs="0"/>
 *         &lt;element name="CustodianReferences">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustodianReference" type="{}CustodianReference" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Exceptions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Exception" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="code" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="-2"/>
 *                                 &lt;enumeration value="-1"/>
 *                                 &lt;enumeration value="0"/>
 *                                 &lt;enumeration value="1"/>
 *                                 &lt;enumeration value="2"/>
 *                                 &lt;enumeration value="3"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TimeStamp" type="{}ISO8601"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustodianResponse", propOrder = {
		"agentReference",
		"messageType",
		"orderStatus",
		"certificateType",
		"certificateText",
		"custodianReferences",
		"exceptions",
		"timeStamp"
})
@XmlRootElement(name = "CustodianResponse")
public class CustodianResponse {

	@XmlElement(name = "AgentReference", required = true)
	protected String agentReference;
	@XmlElement(name = "MessageType", required = true)
	@XmlSchemaType(name = "string")
	protected MessageType messageType;
	@XmlElement(name = "OrderStatus", required = true)
	protected CustodianResponse.OrderStatus orderStatus;
	@XmlElement(name = "CertificateType")
	@XmlSchemaType(name = "string")
	protected CertificateType certificateType;
	@XmlElement(name = "CertificateText")
	protected String certificateText;
	@XmlElement(name = "CustodianReferences", required = true)
	protected CustodianResponse.CustodianReferences custodianReferences;
	@XmlElement(name = "Exceptions")
	protected CustodianResponse.Exceptions exceptions;
	@XmlElement(name = "TimeStamp", required = true)
	protected String timeStamp;

	/**
	 * Gets the value of the agentReference property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAgentReference() {
		return agentReference;
	}

	/**
	 * Sets the value of the agentReference property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAgentReference(String value) {
		this.agentReference = value;
	}

	/**
	 * Gets the value of the messageType property.
	 * 
	 * @return possible object is {@link MessageType }
	 * 
	 */
	public MessageType getMessageType() {
		return messageType;
	}

	/**
	 * Sets the value of the messageType property.
	 * 
	 * @param value allowed object is {@link MessageType }
	 * 
	 */
	public void setMessageType(MessageType value) {
		this.messageType = value;
	}

	/**
	 * Gets the value of the orderStatus property.
	 * 
	 * @return possible object is {@link CustodianResponse.OrderStatus }
	 * 
	 */
	public CustodianResponse.OrderStatus getOrderStatus() {
		return orderStatus;
	}

	/**
	 * Sets the value of the orderStatus property.
	 * 
	 * @param value allowed object is {@link CustodianResponse.OrderStatus }
	 * 
	 */
	public void setOrderStatus(CustodianResponse.OrderStatus value) {
		this.orderStatus = value;
	}

	/**
	 * Gets the value of the certificateType property.
	 * 
	 * @return possible object is {@link CertificateType }
	 * 
	 */
	public CertificateType getCertificateType() {
		return certificateType;
	}

	/**
	 * Sets the value of the certificateType property.
	 * 
	 * @param value allowed object is {@link CertificateType }
	 * 
	 */
	public void setCertificateType(CertificateType value) {
		this.certificateType = value;
	}

	/**
	 * Gets the value of the certificateText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCertificateText() {
		return certificateText;
	}

	/**
	 * Sets the value of the certificateText property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCertificateText(String value) {
		this.certificateText = value;
	}

	/**
	 * Gets the value of the custodianReferences property.
	 * 
	 * @return possible object is {@link CustodianResponse.CustodianReferences }
	 * 
	 */
	public CustodianResponse.CustodianReferences getCustodianReferences() {
		return custodianReferences;
	}

	/**
	 * Sets the value of the custodianReferences property.
	 * 
	 * @param value allowed object is {@link CustodianResponse.CustodianReferences }
	 * 
	 */
	public void setCustodianReferences(CustodianResponse.CustodianReferences value) {
		this.custodianReferences = value;
	}

	/**
	 * Gets the value of the exceptions property.
	 * 
	 * @return possible object is {@link CustodianResponse.Exceptions }
	 * 
	 */
	public CustodianResponse.Exceptions getExceptions() {
		return exceptions;
	}

	/**
	 * Sets the value of the exceptions property.
	 * 
	 * @param value allowed object is {@link CustodianResponse.Exceptions }
	 * 
	 */
	public void setExceptions(CustodianResponse.Exceptions value) {
		this.exceptions = value;
	}

	/**
	 * Gets the value of the timeStamp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimeStamp() {
		return timeStamp;
	}

	/**
	 * Sets the value of the timeStamp property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTimeStamp(String value) {
		this.timeStamp = value;
	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="CustodianReference" type="{}CustodianReference" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"custodianReference"
	})
	public static class CustodianReferences {

		@XmlElement(name = "CustodianReference", required = true)
		protected List<String> custodianReference;

		/**
		 * Gets the value of the custodianReference property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
		 * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
		 * method for the custodianReference property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getCustodianReference().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getCustodianReference() {
			if (custodianReference == null) {
				custodianReference = new ArrayList<String>();
			}
			return this.custodianReference;
		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Exception" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                 &lt;attribute name="code" use="required">
	 *                   &lt;simpleType>
	 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                       &lt;enumeration value="-2"/>
	 *                       &lt;enumeration value="-1"/>
	 *                       &lt;enumeration value="0"/>
	 *                       &lt;enumeration value="1"/>
	 *                       &lt;enumeration value="2"/>
	 *                       &lt;enumeration value="3"/>
	 *                     &lt;/restriction>
	 *                   &lt;/simpleType>
	 *                 &lt;/attribute>
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"exception"
	})
	public static class Exceptions {

		@XmlElement(name = "Exception", required = true)
		protected List<CustodianResponse.Exceptions.Exception> exception;

		/**
		 * Gets the value of the exception property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
		 * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
		 * method for the exception property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getException().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link CustodianResponse.Exceptions.Exception }
		 * 
		 * 
		 */
		public List<CustodianResponse.Exceptions.Exception> getException() {
			if (exception == null) {
				exception = new ArrayList<CustodianResponse.Exceptions.Exception>();
			}
			return this.exception;
		}


		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *       &lt;attribute name="code" use="required">
		 *         &lt;simpleType>
		 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *             &lt;enumeration value="-2"/>
		 *             &lt;enumeration value="-1"/>
		 *             &lt;enumeration value="0"/>
		 *             &lt;enumeration value="1"/>
		 *             &lt;enumeration value="2"/>
		 *             &lt;enumeration value="3"/>
		 *           &lt;/restriction>
		 *         &lt;/simpleType>
		 *       &lt;/attribute>
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				"value"
		})
		public static class Exception {

			@XmlValue
			protected String value;
			@XmlAttribute(name = "code", required = true)
			protected String code;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setValue(String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the code property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCode() {
				return code;
			}

			/**
			 * Sets the value of the code property.
			 * 
			 * @param value allowed object is {@link String }
			 * 
			 */
			public void setCode(String value) {
				this.code = value;
			}

		}

	}


	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="code" use="required" type="{}OrderStatusCode" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"value"
	})
	public static class OrderStatus {

		@XmlValue
		protected String value;
		@XmlAttribute(name = "code", required = true)
		protected OrderStatusCode code;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the code property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public OrderStatusCode getCode() {
			return code;
		}

		/**
		 * Sets the value of the code property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setCode(OrderStatusCode value) {
			this.code = value;
		}

	}

}
